### ISSUE TITLE
SID Sync

### ISSUE THREAD

**Issue by strebl** [Adldap2/Adldap2#106]
I need to sync the SID. Therefore I'm doing something like that:
```php
/**
 * Set the user SID.
 */
public function setSidAttribute($value)
{
    $this->attributes['sid'] = Utilities::binarySidToText($value);
}
```

Is there a reason to store the SID in binary? If not, maybe that's something you could do behind the scenes?

**Comment by stevebauman** [comment]
I'm not really sure of the question. To be honest, I've never played with modifying an objects SID so I'm not sure what's necessary here...

**Comment by strebl** [comment]
If your organisation allows to rename users (samaccountname too), it's kinda hard to recognize the user. Therefore I sync the users SID, because it's the only attribute which shouldn't change.
But I think it makes no sense to save the SID as binary, therefore I transform the SID to text.

How do you guys handle these tasks? Renaming of a user and storing the SID.

**Comment by ChadSikorra** [comment]
@strebl It's actually better to store the user's GUID, as that is guaranteed to never change. Interesting read: https://technet.microsoft.com/en-us/library/cc961625.aspx . I did something similar for a project, as far as always referencing the user by a unique ID rather than their username.

Both the GUID and the SID take a a bit of manipulation to display in their "proper" string format, or at least the form we are all familiar with. I don't see a function yet for displaying the GUID in string form. But you essentially have the unpack it to a hex, then parse out the sections to construct its string form. Fun, huh?

**Comment by jspringe** [comment]
For the record - in the current `5.2` release there is a Utility method for decoding the GUID format `Utilities::binarySidToText($guid)`. It says `SID` but it looks to be the same method used for `GUID`. Try it out - I'll be testing it tomorrow (2/12/2016) as this is something I need.

**Comment by strebl** [comment]
Yeah, that utility method was available even in the old Adldap library.
