### ISSUE TITLE
Fallback to "local" login if AD fails

### ISSUE THREAD

**Issue by modbase** [Adldap2/Adldap2#135]
Is there a way to "locally" login e.g. an admin user if AD login is temporary not possible? For example: if username == admin and bcrypt(password) == password in DB, then login user.

This can be particulary useful for local development when no domain controller is available.

**Comment by franktbc** [comment]
+1

**Comment by stevebauman** [comment]
The only way we could achieve this easily would be utilizing and building this into the framework options for Adldap2 (such as [Adldap2 Laravel](http://www.github.com/Adldap2/Adldap2-Laravel).

I personally have no intentions of building this into the base Adldap2 repository to be framework agnostic since the large majority of developers use frameworks, and we can work with those so their more functional and flexible.

**Comment by modbase** [comment]
Oh my, I posted this at the wrong repository. I indeed meant [Adldap2-Laravel](http://www.github.com/Adldap2/Adldap2-Laravel)

**Comment by stevebauman** [comment]
Ok, no problem!

**Comment by stevebauman** [comment]
Added: https://github.com/Adldap2/Adldap2-Laravel/commit/e19ce8dc34e10b8ad53f95acc3c30cb3410842cd
