### ISSUE TITLE
Question about setPassword method.

### ISSUE THREAD

**Issue by jspringe** [Adldap2/Adldap2#181]
Is it on purpose that the [setPassword ](https://github.com/Adldap2/Adldap2/blob/v5.2/src/Models/User.php#L775) simply returns $this->addModification? If so what's right way to use that method? I ask because I expected it to work the same as [changePassword](https://github.com/Adldap2/Adldap2/blob/v5.2/src/Models/User.php#L807) and return bool / throw exceptions.

If not I have a PR ready to be submitted.

**Comment by stevebauman** [comment]
Yes, this is how the `setPassword()` method was intended to function. Since all other `set()` methods return the `setAttribute()` method, which return the underlying model instance, the `addModification()` method also returns the underlying model instance.

The `setPassword()` is intended to be separate from the `changePassword()` method, because the change password pushes the changes immediately to the LDAP connection and returns the result, however the `setPassword()` method just applies the batch modifications necessary, then you're required to use the `save()` method.

This is for method chain-ability. For example:

```php
$user->setPassword('12345')->setName('John Doe')->setCn('Doe, John')->save();
```
