### ISSUE TITLE
Guidance / Testing needed for Creation / Modification of LDAP Entries

### ISSUE THREAD

**Issue by stevebauman** [Adldap2/Adldap2#21]
Due to my environment permission restrictions I can't run my own tests on my LDAP server to play with creation and modification of groups / users / folders etc. This is the last remaining large piece of this package that needs documentation and tests, however I'm not sure if I should move this whole process of creation and modifications to an object oriented type of API.

An example of what I think would be great:

    $user = $ad->user()->new();

    $user->username('John Doe');
    $user->email('jdoe@acme.com');
    $user->save();

I can do this now, but this would offer inconsistent results with methods such as `find()`. Users would think that they could then perform operations like this (but can't since a raw array is returned):

    $user = $ad->user()->find('jdoe');

    $user->username('Sue Doe');
    $user->save();

If objects were returned with methods such as `find()` and `all()`, this would allow us to really enhance the API and functionality, but then it breaks all compatibility with previous users. I'm stuck in the middle here.

Any feedback and/or help in this area would be amazing. Please let me know your thoughts!

**Comment by strebl** [comment]
I was googling around and saw the Microsoft Azure Active Directory service which is free for 10 users and 500k objects. But I have no idea if it's available with LDAP and if it is comparable to a normal Active Directory. But maybe something worth to look at.

My question is, how do you test your apps if they have modification / creation ability? That's something I asked myself a lot if I have deal with that problem in the future.
Now you can take Adldap2 which is well tested, but that's the only well tested easy to use ldap package I know^^ And I think I would write some implementation tests too because every directory is different and really hard to test.

I love the API changes you talking about. Especially the the enhanced version you talking about. It seems you love Laravel's Eloquent too :smiley:
My opinion: If you don't change it now, you can't change it for a while. Now we are jumping to a new major version which I think is the best moment to break BC. There are no version "*" users which would be affected because every user has to switch to Adldap2 actively (at least at the moment). Therefore they will and have to inform them self about changes. That's the reason it's the best moment for these changes.
Just not to much BC breaking changes, that could hurt the adoption.

**Comment by wunc** [comment]
Unfortunately, I also don't have access to an LDAP server with write access. Another option would be to install a trial of Windows Server in a VM to test against.

I also like your proposal for creations and modifications, but am a little torn on whether it's too much.

One thing to consider: If you make `find()` and `all()` like that, how are multiple results handled? Would you need a collection object? (sorry, I haven't checked the code for awhile, so don't know if there's already an easy answer to this)

As for them returning an object directly, if you are using Laravel as the model for this, you could make the proposed change and then provide some `toArray()` and `toJson()` serializers, which I think might suffice. That way you can stay consistent with returning user objects but still make it easy to fix any existing calls that are expecting an array output (just append `->toArray()` onto the end of the existing call), assuming that the serializer returns the same format that is currently returned. Again, I'm torn on this, but I'm leaning towards saying "just do it" :)

**Comment by strebl** [comment]
:+1: for Laravel collections.

**Comment by stevebauman** [comment]
@strebl Thanks for the recommendation of Azure, though it looks like they don't support LDAP (at least not yet). [Link](http://stackoverflow.com/questions/19562291/use-windows-azure-active-dirctory-for-apache-ldap-authentication)

For testing creations / modifications, all we really need to test is that the information passed to the LDAP connection is correct. For devs that experience issues with that, I believe they'd need to troubleshoot their own server. Though all fields on objects such as a user, will need to be modifiable so we can also support open source LDAP solutions such as OpenLDAP.

I agree though, this is the best time for the largest breaking changes, and to move forward with a simple, clean intuitive API would be awesome. You're also right, I do love laravel's eloquent API :smile:, it's a great looking API, and makes sense.

@wunc Yup you're right, I was planning on making a collection object extremely similar to a laravel collection, and those helpers would go along with it. I think it's time to rip off the bandaid and go for it. I **really** want a clean, easy to use API, that makes working with LDAP fun, and not a PITA.

I really appreciate your comments and feedback guys, I'll start on this right now.
