### ISSUE TITLE
users search not working

### ISSUE THREAD

**Issue by markpurser** [Adldap2/Adldap2#214]
Hi, I'm trying to search all users using the following code. What is the difference between doing a `search()->all()` and doing a `search()->select([])->get()`? Is select broken? Many thanks in advance
```
    $config = [
        'account_suffix'        => '@gatech.edu',
        'domain_controllers'    => ['whitepages.gatech.edu'],
        'base_dn'               => 'dc=whitepages,dc=gatech,dc=edu',
        'admin_username'        => '',
        'admin_password'        => '',
    ];

    $ad = new \Adldap\Adldap($config);

    // works
    dd($ad->search()->all());

   // doesn't work - returns empty list
   dd($ad->users()->all());

   // doesn't work - returns empty list
   dd($ad->search()->select([])->get());
```

**Comment by stevebauman** [comment]
> Is select broken?

No, I'm actually going to remove this example from the docs.

This is due to entries on their server being returned that do not contain an object class.

Using `search()->all()` would return all entries, regardless of their object class (you're most likely seeing an array of `Adldap\Models\Entry`).

However, when you scope the query by specifying `users()`, it tries to search their server **by object class**, which would yield no results since their returned entries don't contain one that's visible (most likely for security purposes).

For example of a returned search result from their server:

```php
// No 'objectclass' attribute visible.
#attributes: array:3 [▼
    "cn" => array:1 [▼
        0 => "offcampus"
    ]
    0 => "cn"
    "dn" => "cn=offcampus,dc=whitepages,dc=gatech,dc=edu"
]
```
