### ISSUE TITLE
Call to undefined method Adldap\Adldap::authenticate()

### ISSUE THREAD

**Issue by rpwang** [Adldap2/Adldap2#263]
Hi,

No luck in authenticating as an user with ldap credentials. The connection to ldap server works now. It seems that I missed an error during the composer update...
```
> php artisan optimize
PHP Fatal error:  Call to undefined method Adldap\Adldap::authenticate() in /opt/app/ldap-app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 221


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Adldap\Adldap::authenticate()

```

These are in my composer file:
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "adldap2/adldap2-laravel": "2.0.*",
        "adldap2/adldap2": "6.0.*

**Comment by stevebauman** [comment]
Hi @rpwang,

If you're trying to upgrade to the new Adldap2 version and have the `auto_connect` configuration enabled for your connection, this needs to be temporarily disabled when you run `composer update`. This is due to a new API.

In short, disable `auto_connect` in your `config/adldap.php` configuration file, run `composer update`, and you should be fine.

Also, this line:

```json
"adldap2/adldap2": "6.0.*
```

Is redundant when requiring:

```php
"adldap2/adldap2-laravel": "2.0."
```

As the required Adldap2 version is automatically required and downloaded when downloading the laravel package.

**Comment by rpwang** [comment]
Thanks! The app is working fine :+1:
