### ISSUE TITLE
adldap2/adldap2 : Doesn't work for LDAP servers without SSL

### ISSUE THREAD

**Issue by Dasuntha** [Adldap2/Adldap2#299]
Hi,

Our LDAP server hasn't setup for SSL. I am trying to use adldap2 library to connect to LDAP server to access Active Directories. **It didn't work due to following error,**

Basically this is working fine for me (without adldap2  library):
                    ldap_connect ( 'ldap.example.com', 'port');

However in adldap2/adldap2, it put  "**ldap://** " in front of the host name. Therefore it doesn't work.
See the getProtocol function from Ldap.php
   /**
     * Returns the LDAP protocol to utilize for the current connection.
     *
     * @return string
     */
    protected function getProtocol()
    {
        return $this->isUsingSSL() ? $this::PROTOCOL_SSL : **$this::PROTOCOL**;
    }

You need to remove  "$this::PROTOCOL". It should be blank for TLS connections. 

Please see the PHP manual here
http://php.net/manual/en/function.ldap-connect.php

<?php

// LDAP variables
$ldaphost = "ldap.example.com";  // your ldap servers
$ldapport = 389;                 // your ldap server's port number

// Connecting to LDAP
$ldapconn = ldap_connect($ldaphost, $ldapport)
          or die("Could not connect to $ldaphost");

?>

**There should be no "ldap://" if its not SSL connection.** 

I hope you will fix this issue soon. This library is really useful one. Thank a lot.

**Comment by stevebauman** [comment]
Hi @Dasuntha.

Connecting to LDAP via an URI is completely valid. Here's the RFC:

https://www.ietf.org/rfc/rfc2255.txt

> There should be no "ldap://" if its not SSL connection.

This just isn't true. If your connecting via an SSL connection with an LDAP URI, you actually need to specify `ldaps://`. Otherwise, for non-SSL connections, you utilize the syntax `ldap://`.

My AD server doesn't have SSL enabled, Adldap2 has been working great.

Please check your configuration.
