### ISSUE TITLE
Where to put documentation?

### ISSUE THREAD

**Issue by samwilson** [Adldap2/Adldap2#3]
Anyone got thoughts about documentation?

There is currently:
* http://adldap.sourceforge.net/wiki/doku.php?id=documentation&do=index
* https://github.com/adldap/adLDAP/wiki

One goal could be to have both user documentation and auto-generated API browsing at https://adldap2.github.io. The latter could be produced by e.g. phpdoc, and the former by e.g. http://sphinx-doc.org/. Or perhaps a service like http://readthedocs.org is better?

Then, of course, comes the more meaningful task of getting the docs up to date. :) Not that they're terrible at the moment, but they do need to be consolidated.

**Comment by stevebauman** [comment]
Yea I agree :thumbsup:. I can start writing the hang written documentation, however I've actually never used an API doc generator, so any help there would be awesome.

**Comment by samwilson** [comment]
Okay, cool.

Could you create the adldap2/adldap2.github.io repository? See https://pages.github.com/#user-site

I can get the API docs set up. I suggest a URL structure that allows each released minor version to be kept online, as well as *master*; something like: `adldap2.github.io/api/master`, `adldap2.github.io/api/4.0`, `adldap2.github.io/api/4.1`, `adldap2.github.io/api/5.0`, etc. Sound okay?

As for the user guide, I just noticed that phpDocumentor itself is using Sphinx, so maybe that'd be a good choice? But for now I'll just see about the API docs.... phpDocumentor is good at highlighting errors in docblocks too, so that'll help improve the codebase. :)

**Comment by stevebauman** [comment]
Done! You should have full write access to the adldap2.github.io repository.

I agree with the API structure. Also, [Sami](https://github.com/fabpot/sami) does great API documentation, using Laravel as an [example](http://laravel.com/api/4.2/), I've personally seen many more projects using Sami than I have phpDocumentor, however if it's easier to set up / use phpDocumentor, then I have no issues with it.

**Comment by samwilson** [comment]
Thanks! I'll investigate Sami; I like the Laravel docs.

Speaking of Laravel, do you develop with it? What LDAP package do you use?

It occured to me tat we could add a list somewhere here of packages that use adLDAP, such as those for Laravel, and other frameworks and CMSs. What do you think? There's just so much fragmentation it seems! It'd be nice to bring some order to it.

**Comment by strebl** [comment]
@samwilson I like the style of http://readthedocs.org

Speaking of Laravel, I used [ccovey/ldap-auth](https://github.com/ccovey/ldap-auth).
But I had to [fork](https://github.com/strebl/ldap-auth) this package because it seems ccovey did stop maintain it and I needed Laravel 5 support.
It's a ldap authentication provider for Laravel.
Maybe we could provide a clean and tested (!) Laravel package under the adLDAP2 organisation if the most of us using Laravel.

**Comment by stevebauman** [comment]
@samwilson Yup, I develop mostly all of my packages with Laravel. I use the package I created actually called [Corp](https://github.com/stevebauman/Corp), it's sort of a 'helper' package, as it merely just allows you to have a configuration file and helper methods using the facade (such as `Corp::authenticate()`), with some other minor functionality using Windows COM (allows you to modify LDAP passwords without SSL / TLS).

I agree with the framework and CMS list, that's a great idea!

@samwilson Offering framework packages under the Adldap2 organization would be awesome, though I could only develop for Laravel since that's where the majority of my experience lies.

**Comment by samwilson** [comment]
(I've created #9 to track a Laravel package.)

I've not got a chance just now to look at it, but the script here seems useful for keeping a gh-pages API doc up to date: https://github.com/google/google-api-nodejs-client/issues/245

**Comment by ChadSikorra** [comment]
While not for API doc generation, I'd recommend taking a look at MkDocs (http://www.mkdocs.org/). Its beauty is really in its simplicity. You can generate a site from a simple 'docs/' directory structure of markdown files. The added bonus is the same doc files look good when viewed on normal Github too.

**Comment by wunc** [comment]
I would agree with http://readthedocs.org/ too. It is an additional "thing", but it seems fairly popular.
