### ISSUE TITLE
Control warnings

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2#310]
Hi,
I have a couple of warnings using the component. 

I know  I can hide message errors like warnings or notice, but, maybe, you can control the generation or this warnings. If not, simply close the issue, not problem..

1. If you create a DN from LDAP, you get a warning for the exists of methods. Example:
    ```php
    // DN from LDAP: $user['dn'] = uid=test.user,ou=company,ou=foo,ou=bar'
    $dnLDAP = new \Adldap\Objects\DistinguishedName($user['dn']);
    ```
    `Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap\Objects\DistinguishedName' does not have a method 'addUid' in \vendor\adldap2\adldap2\src\Objects\DistinguishedName.php on line 230`

2. If you search for a DN doesn´t exist, you get two warnings:
    ```php
    try {
        $search->findByDnOrFail('ou=this,ou=dn,ou=not,dc=exists,dc=com');   
    } catch (Adldap\Exceptions\ModelNotFoundException $e) {
        echo "Catch exception";
    }
    ```
    `Warning: ldap_read(): Search: No such object in \vendor\adldap2\adldap2\src\Connections\Ldap.php on line 237`

    `Warning: ldap_get_entries() expects parameter 2 to be resource, boolean given in \vendor\adldap2\adldap2\src\Connections\Ldap.php on line 113`

Thank you!! :smiley:

**Comment by stevebauman** [comment]
Hi @Albvadi, thanks for reporting this!

1. This is definitely a bug, I'm fixing this now. This only occurs with OpenLDAP because distinguished names contain more attributes than just `cn`, `dc`, and `ou` (these are the only attributes that exist in a dn in active directory).

2. Where do you receive this error? I don't receive any warnings when I catch the `ModelNotFoundException`? Do you happen to have a higher level of error reporting on your PHP install?

Again, thanks for the report with the detailed information!

**Comment by Albvadi** [comment]
> Where do you receive this error? I don't receive any warnings when I catch the ModelNotFoundException? Do you happen to have a higher level of error reporting on your PHP install?

It´s very strange...
I´m testing with differents DNs and get different results...

Examples: 
My base dn is: `'dc=cdatexlab,dc=net'`
```php
try {
    $provider->search()->findByDnOrFail('ou=this,ou=dn,ou=not,ou=exists,dc=cdatexlab,dc=net');   
} catch (Adldap\Exceptions\ModelNotFoundException $e) {
    echo "Catch exception";
}

/** RESULT  
Warning: ldap_read(): Search: No such object in \vendor\adldap2\adldap2\src\Connections\Ldap.php on line 237
Warning: ldap_get_entries() expects parameter 2 to be resource, boolean given in \vendor\adldap2\adldap2\src\Connections\Ldap.php on line 113
Catch exception
*/
```
```php
try {
    $provider->search()->findByDnOrFail('ou=this,ou=dn,ou=not,dc=exists,dc=com');   
} catch (Adldap\Exceptions\ModelNotFoundException $e) {
    echo "Catch exception";
}

/** RESULT  
Catch exception
*/
```
In both cases, DN not exists, but the first launch warnings with the exception and the second don´t.
Error reporting level it´s the default in xampp: `error_reporting = E_ALL | E_STRICT`

**Comment by stevebauman** [comment]
I'm now receiving the same thing, it looks like your base DN needs to be correct, but what your searching for needs to be non-existent.

Searching for this displays the error because your base DN exists in LDAP (`dc=cdatexlab,dc=net`):

```
ou=this,ou=dn,ou=not,ou=exists,dc=cdatexlab,dc=net
```

However in the second search the base DN does not exist. This is definitely not intended though, fixing now, thanks!
