### ISSUE TITLE
How to create a user?

### ISSUE THREAD

**Issue by dico** [Adldap2/Adldap2#330]
Hi. I'm trying to create a new user with Adldap2, but i'm struggling a bit. I'm testing with one of the example codes:

```
$user = $this->provider->make()->user();

$user->setCommonName('Daisy Duck');
$user->setDisplayName('Daisy Duck');
$user->setFirstName('Daisy');
$user->setLastName('Duck');
$user->setTitle('Girlfriend of Donald Duck');
$user->setDepartment('Andeby');
$user->setInfo('Daisy was introduced in the short film Mr. Duck Steps Out (1940)');
$user->setInitials('DD');
$user->setPhysicalDeliveryOfficeName('Clubhouse office');
$user->setTelephoneNumber('12345678');
$user->setCompany('Mickey Mouse Clubhouse');
$user->setPassword('Monday123');
$user->setStreetAddress('Duckburg 123');
$user->setPostalCode('1234');

$dn = $user->getDnBuilder();

$dn->addCn($user->getCommonName());
$dn->addOu('Testusers');
$dn->addDc('login');
$dn->addDc('domain');
$dn->addDc('local');

// Returns 'cn=John Doe,ou=Accounting,dc=corp,dc=acme,dc=org'
echo $dn->get();

// The DistinguishedName object also contains the __toString() magic method
// so you can also just echo the object itself
echo $dn;
$user->setDn($dn);
$user->save();

if ($user->create()) {
	echo "User was created";
} else {
	echo "Issue creating user";
}
```

This gives me an error in the apache log:
`[Wed Oct 05 12:46:49.598522 2016] [:error] [pid 24344] [client 172.27.10.101:54592] PHP Warning:  ldap_add(): Unknown attribute in the data in /var/www/intranett.dev.mydomain.local/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 261`

But it looks like the user is created successfully in AD.

I also have some other questions like:
- Where do I set the username/logon-name? Is there a doc/list of the attributes, or do I have to browse the source?
- Why is the user disabled when I create the user? Can I set the user as enabled when I create it?

(Update: Using adldap2 v6.1.8)

**Comment by stevebauman** [comment]
Hi @dico,

You're saving the user, and then creating the user. The save method already performs the create for you. This is mentioned in the docs:

https://github.com/Adldap2/Adldap2/blob/master/docs/models.md#saving

```php
// You already saved the user here:
$user->save();

if ($user->create()) { // Now you're creating the user
    echo "User was created";
} else {
    echo "Issue creating user";
}
```

> Where do I set the username/logon-name? Is there a doc/list of the attributes, or do I have to browse the source?

You're looking for the `setAccountName()` method:

```php
$user->setAccountName('jdoe');
```

> Why is the user disabled when I create the user? Can I set the user as enabled when I create it?

You need to set the users `userAccountControl`. By default, all users are disabled. This isn't caused by Adldap, this is by default in Active Directory. If you're not sure how to utilize AD's account control, it might be worth a quick google search since there's a lot of options I can't explain here.

But here's an example of enabling a user using an [AccountControl](https://github.com/Adldap2/Adldap2/blob/master/src/Objects/AccountControl.php) object:

```php
$ac= new \Adldap\Objects\AccountControl();

$ac->accountIsNormal();

$user->setUserAccountControl($ac);
```
