### ISSUE TITLE
Sanitizing user input for password change

### ISSUE THREAD

**Issue by sulzer** [Adldap2/Adldap2#384]
Rather a question than an issue:

I am using a public web form where the AD password can be changed.  The code is as follows:

`$user = $adldap->search()->find($_SESSION['username']);`
`$user->setPassword($userInput)`

Is there any danger in accepting $userInput as it is posted or should I sanitize the input?  The issue when using common sanitizing techniques (e.g trim) is that the password may get changed in the background, without the user's knowledge.

Thanks for any guidance!

**Comment by stevebauman** [comment]
Hi @sulzer,

The only thing I would check against before allowing a user to change their password is the length / complexity that aligns with your LDAP server.

This would be to avoid an error being returned from your LDAP server due to it not meeting password requirements.

I see no issue with passing in direct input from the user, and I wouldn't run any trims on the password since a user may want to use spaces inside their password.

If you have any further questions just give me a shout!

**Comment by sulzer** [comment]
Great, thanks @stevebauman!
