### ISSUE TITLE
Consistency between '' and null

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2#406]
- Adldap2 Version: 7.0.15
- LDAP Type: OpenLDAP
- PHP Version: 7.0.9

### Description:
In the configuration array, the `admin_username` property for OpenLDAP, generally always have the complete dn. If you don´t have the `admin_account_prefix` and `admin_account_suffix`, the properties `account_prefix` and `account_suffix` are added to the admin bind, resulting in a incorrect username. Everything is correct so far.

But if you have `admin_account_prefix` and `admin_account_suffix` setted without content (`''`), has the same effect that not set the properties, and Adldap2 add the properties `account_prefix` and `account_suffix` to the admin bind again, resuting again in a incorrect username.

### Steps To Reproduce:
I think, if you dont set the properties `admin_account_prefix` and `admin_account_suffix`, you should use the `account_prefix` and `account_suffix` properties, but if you set `admin_account_prefix` and `admin_account_suffix` (even without content) you shoud use this and not ignore...

One example it´s the configuration in my [PreLoginLdapMiddleware](https://github.com/Adldap2/Adldap2-Laravel/issues/117#issuecomment-224550280). If I don´t set the space in 'admin_account_suffix', the `$account_suffix` obtained in search at point 5, is added to the admin username too...

P.S: Sorry if you don´t understand very wel... It's a bit lousy to explain because of my language... :sweat:

**Comment by stevebauman** [comment]
Hey @Albvadi, I've encountered this myself, and I'll label this as a bug because I agree it needs to be resolved.

This could cause issues with current configurations so this is a breaking change that will need to be released in a `v7.2.*` version.

**Comment by szaqal83** [comment]
This bug is back in v8.0.0, after upgrade from 7.0.15 without changing any of my confs I get:

Fatal error: Uncaught Adldap\Auth\BindException: Invalid credentials in /var/www/html/test/ad/vendor/adldap2/adldap2/src/Auth/Guard.php:76 Stack trace: #0 /var/www/html/test/ad/vendor/adldap2/adldap2/src/Auth/Guard.php(89): Adldap\Auth\Guard->bind('xxx', 'XXXXXX', '', '') #1 /var/www/html/test/ad/vendor/adldap2/adldap2/src/Connections/Provider.php(211): Adldap\Auth\Guard->bindAsAdministrator() #2 /var/www/html/test/ad/vendor/adldap2/adldap2/src/Adldap.php(129): Adldap\Connections\Provider->connect(NULL, NULL) #3 /var/www/html/test/ad/ad.php(58): Adldap\Adldap->connect() #4 {main} thrown in /var/www/html/test/ad/vendor/adldap2/adldap2/src/Auth/Guard.php on line 76

my conf array is:

`$config = array(
	'account_suffix' => '@xxx.xx',
	'base_dn' => 'dc=XXX,dc=XX',
	'domain_controllers' => array('xxx.xx'),
	'admin_username' => $_SERVER['PHP_AUTH_USER'],
	'admin_password' => $_SERVER['PHP_AUTH_PW'],
	'use_tls' => true,
	'custom_options' => array(
		// See: http://php.net/ldap_set_option
		LDAP_OPT_X_TLS_REQUIRE_CERT => LDAP_OPT_X_TLS_ALLOW
    )
);
$ad = new \Adldap\Adldap();
$ad->addProvider($config);
$provider = $ad->connect();
`

it started to work after adding:

`'admin_account_prefix'  => null,
    'admin_account_suffix'  => null,`

to the conf array, setting admin_account_* to empty string also does affect same exception as above :(.

**Comment by stevebauman** [comment]
Hi @szaqal83, going to change the defaults in the configuration array so users upgrading won't encounter this issue.

Thanks!
