### ISSUE TITLE
Ability to run a `notWhere` clause?

### ISSUE THREAD

**Issue by ElvenSpellmaker** [Adldap2/Adldap2#418]
- Adldap2 Version: 7.0.*
- LDAP Type: AD
- PHP Version: N/A

### Description:
I believe I am missing something but I can't locate it in the code or documentation.

The problem I have is that I need to do a strict greater than or less than query within the LDAP, in order to do this I can use the workaround, for example for strict less than:
```php
...
	->where('attribute', '<=', <value>)
	->where('attribute', '!', <value>)
...
```

However I'd like to do this in one line if possible, but I cannot find a way to do a `notWhere`, (negated where), which in LDAP syntax would look like the following: `!(attribute >= threshold)`.

Arguably it's less clear with a negated where, but it seems that this feature that's available in LDAP syntax is missing from the library.

Is this currently possible in the library?

Thanks.

**Comment by stevebauman** [comment]
Hi @ElvenSpellmaker, there's several `whereNot` methods that you can utilize. However, there is currently no way to create a `whereNotGreaterThan` or `whereNotLessThan` query using the query builder.

You can either:

- Call `$builder->whereNotEquals('field', 'value');`
- Call `$builer->where('field', '!=', 'value');`
- Call `$builder->rawFilter('(!(attribute<=value)');`

I'll leave this open so I can add this into the query builder.

**Comment by stevebauman** [comment]
Hi @ElvenSpellmaker, I've just added this in: https://github.com/Adldap2/Adldap2/commit/8f4d9698afda27d99dbf0dca0c4643f367dbd7d4

`v7.1` will be released shortly due to some small API changes, but you will be able to perform your above query like so:

```php
$results = $query->notFilter(function ($query)) {
    $query->where('attribute', '<=', 'value');
})->get();
```

This produces the query you're looking for:

```
(!(attribute<=value))
````

I'll close this once `v7.1` is released, but wanted to make sure you're aware that it's been implemented.

Thanks for the suggestion!

**Comment by ElvenSpellmaker** [comment]
Thanks! =)
