### ISSUE TITLE
Add custom query to search

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#42]
Hi !

It could really interesting to have the ability to add a custom query in search() object, something like that could be really usefull : 

```php
$adldap->search()->where('cn', '!', 'Jon')->customQuery('(userAccountControl:1.2.840.113556.1.4.803:=2)')->get();
```

I saw that you can pass a custom query but actually we have the obligation to pass the query as string and we lose all class functionalities (like select, where, orWhere, ...)

Thanks for your help

**Comment by ciadch** [comment]
In the same way and I don't know if it's possible but if you can return ADLDAP object in search query() it could be really interessting. With that we can use all the methods in search class.

Thanks

**Comment by stevebauman** [comment]
This could be really difficult to implement. We'd need to assume what kind of query the dev is looking to run as we'd need to concatenate both query strings. For example, in your example above, would the result query appear as:

    (!(cn=Jon)(userAccountControl:1.2.840.113556.1.4.803:=2))

Or:

    (&(userAccountControl:1.2.840.113556.1.4.803:=2)(!(cn=Jon)))

I'm mostly just worried about how the query string is assembled, as when the dev inserts a custom string, they'd need to be aware of the other conditions inside the current query. 

 I'm definitely not against this, but I'll see what I can do.

**Comment by stevebauman** [comment]
> In the same way and I don't know if it's possible but if you can return ADLDAP object in search query() it could be really interessting. With that we can use all the methods in search class.

I'm not sure what you mean by returning the Adldap object with the search `query()` method? Why would you want the Adldap instance returned?

**Comment by ciadch** [comment]
(first post) : I understand it's a bit complicated but in a first version if  it's possible to add the query after the rest it could be interessting and really usefull. And the answer is the second one : 
```
(&(userAccountControl:1.2.840.113556.1.4.803:=2)(!(cn=Jon)))
```` 

(second post) : Forget it, I found the way to use query correctly :-) !

Thanks !

**Comment by sroutier** [comment]
+1

Nuts! Exact same question that I was going to ask about last night, but I decided to run a few more test first! Steve, thanks for your library. Been using it for a while, first v4, but now upgrading to v5. Awesome lib. 
I have this new-ish project where I need to allow partial configuration of the search filter/query, for users and groups. something like ```user_filter=(&(objectClass=inetOrgPerson)(customattribute=somevalue))```, same idea for groups. V4 has the filter pretty hard coded, and I guess will now be on the back burned in favour of v5, so I upgraded to v5. V5 allows us to get the query, to re-use it later, but once the query set, we loose the ability to add more '->where' clauses and have the new query re-assembled before execution.

So my solution was to build a config vars like that:

```
user_filter=(&(objectcategory=person)(samaccountname=%u)(!(samaccountname=adm*)))
```

In the code after having replaced the '%u' placeholder with the value searched for, I call:

```
$adResults = $adldap->users()->search()->select($ldapFields)->query($ldapQuery);
```

But that does not have the expected behaviour. The function calls returns a result, helping to validate that the query has no syntax error, but when the searched username/samaccountname is 'admin' it should not return anything (empty array or false), has the filter/query explicitly denies it. I have tried multiple combination of simple and complex filters with and without escaping the values, and it looks like when the query gets too complicated the engine start ignoring some rules.

Any ideas?

Thanks.
/S

**Comment by stevebauman** [comment]
@sroutier Hey thanks for commenting. I ran your query just fine on my server and received the expected results:

```php
$username = 'jdoe';

$query = "(&(objectcategory=person)(samaccountname=$username)(!(samaccountname=adm*)))"

$results = $ad->search()->query($query);
```

I'm not sure I 100% understand the issue you're encountering? When you pass in a query into the `search()->query()` method, that's sending it directly into PHP's native `ldap_seach()` method. The query isn't touched.

I'm might not be understanding your issue here, so definitely let me know, thanks!

**Comment by stevebauman** [comment]
@ciadch I'm rebuilding the query builder as we speak (don't worry, methods will stay the same, you won't notice a difference). It'll be a `v5.1` update so keep an eye out. I'm hoping to include this in.

**Comment by sroutier** [comment]
Puzzled.... Thanks.
I swear something was not working right before, but now it does... I must have gotten confused in my LDAP filter voodoo...
Eagerly awaiting ```v5.1```.
Thank again.

**Comment by stevebauman** [comment]
Great to hear, thanks for letting me know.

**Comment by ciadch** [comment]
@stevebauman Thanks for your job ! I keep an eye on the branch.

**Comment by stevebauman** [comment]
`v5.1` will be released shortly with the ability to use `rawFilter()` on the search class:

```php
$ad->search()->where('cn', '=', 'John')->rawFilter('(samaccountname=jdoe)')->get();
```

**Comment by ciadch** [comment]
Awsome ! Thanks for the job ! I wait for the release
