### ISSUE TITLE
Hardcoded Group type hinting

### ISSUE THREAD

**Issue by tortuetorche** [Adldap2/Adldap2#472]
- Adldap2 Version: 8.0.9
- LDAP Type: OpenLDAP
- PHP Version: 7.0

### Description:

Hi,

The `auth()->user()->ldap->getGroups()` is OK since https://github.com/Adldap2/Adldap2/commit/934b11e2a5ea82add9523d6caeb43f5c0415d3e8 but when I try `auth()->user()->ldap->inGroup('toto')`, it throws this error:

```
Type error: Argument 1 passed to Adldap\Models\User::Adldap\Models\Concerns\{closure}() must be an instance of Adldap\Models\Group, instance of Adldap\Models\Entry given
```
From https://github.com/Adldap2/Adldap2/blob/v8.0.9/src/Models/Concerns/HasMemberOf.php#L165

So is it possible to remove the `Group` type hinting in the `HasMemberOf` trait?
https://github.com/Adldap2/Adldap2/blob/v8.0.9/src/Models/Concerns/HasMemberOf.php#L134
https://github.com/Adldap2/Adldap2/blob/v8.0.9/src/Models/Concerns/HasMemberOf.php#L165
https://github.com/Adldap2/Adldap2/blob/v8.0.9/src/Models/Concerns/HasMemberOf.php#L220

Related to #471 

Have a good day,
Tortue Torche

**Comment by stevebauman** [comment]
Going to remove the hinting, thanks for the report!

**Comment by stevebauman** [comment]
This might be tricky since we need to actually validate that we have an instance of a `Group` model so we can verify that the methods exist, since only the `Group` model contains the `addMember` and `removeMember` methods etc.

You will need to create your own model and extend from the `Group` model for these methods to work properly. This is in the documentation for creating your own `Schema`.

This was the original purpose of the `instanceof` checks, and working around it seems really hacky to me.

Looking back, I'm actually going to restore the previous `instanceof` checks. It's significantly faster (%50 faster in tests) rather than using `is_a()` (a previously depreciated method).

**Comment by stevebauman** [comment]
If you require that your organizational units be returned as `Group` models in your application, you will need to modify the `objectClassGroup()` method in the `OpenLDAP` schema, and return `organizationalunit` instead of `groupofnames`.
