### ISSUE TITLE
Get Users of an OU

### ISSUE THREAD

**Issue by Espadonx** [Adldap2/Adldap2#477]
- Adldap2 Version: ^.8 (composer require)
- LDAP Type: Active Directory
- PHP Version: 7.1

### Description: 
hello, I'm in trouble using your library (that seems awesome, and I hope that you can give me an answer).
I have an AD in my organization that reproduce this schema : 
- LOCAL
     - FACTORY_1
          -FAC1_USERS
          -FAC1_COMPUTERS
     - FACTORY_2
          -FAC2_USERS
          -FAC2_COMPUTERS
     - FACTORY_N
          -FAC3_USERS
          -FAC3_COMPUTERS
etc.

I would like to query my AD with adldap2 to get all of my users stored in FAC1_USERS, FAC2_USERS and, why not, not include FAC3_USERS.

I'm trying some query since yesterday but I don't find a way to get my work done...
As an example : 
 $search->select(['cn', 'samaccountname', 'telephone', 'mail']);
    $filters = [
        '(&(distinguishedName=OU=FAC1_USERS,OU=FACTORY_1,OU=ORGANIZATION,DC=ORGANIZATION,DC=local))'
    ];
    $results = $search
            //->users()
            ->rawFilter($filters)
            ->get();

    print_r($results);

But I also don't understand why i'm not getting my select() working ... 

is there any help please ? :) Thank you !

Fabien.

**Comment by stevebauman** [comment]
Hey @Espadonx,

Unfortunately searching through multiple OU's isn't possible (at least, [not without some LDAP trickery](https://stackoverflow.com/questions/9184978/ldap-root-query-syntax-to-search-more-than-one-specific-ou) - which isn't really worth it).

I would grab all users, and then filter through the ones you need, or better yet if you're the LDAP administrator, I would apply a specific group to all users inside the OU's you're looking for, then retrieve the members of that group.

If you're not the administrator, then you'll have to filter the ones you need. Here's how you can do this:

```php
$users = $provider->search()->users()->get();

$filtered = $users->filter(function ($user) {
    $ous = [
        'OU=FAC1_USERS',
        'OU=FAC2_USERS',
        'OU=FAC3_USERS',
    ];

    return str_contains($user->getDn(), $ous);
});
```

This will remove all users from the original result that are not apart of the OU's specified.

This is really the only clean way of doing this, otherwise I would choose the second approach of applying a group membership to all users in the OU's you need to retrieve.

**Comment by Espadonx** [comment]
Hi ! 

Thank you for the answer, I implemented my search on this way. I got all users and I filtered and it works. I just hoped that there was a solution to search through multiple OU but if it's not possible ... 

Thank you again, you helped me a lot.

Fabien.

**Comment by stevebauman** [comment]
Glad I could help @Espadonx! :)
