### ISSUE TITLE
Connection vs Authentication

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#490]
Hi @stevebauman,

Hope you're well ! Juste a little question. I now update Adldap2 to last version and I rewrite my classes. I have now something that I misunderstand.

If I want to authenticate my user, i really use to connect berfore ? I do auth like that 
```php 
  $this->config    = new Configuration\DomainConfiguration(Config::get('ldap_connexion_options'));
  $this->provider = new Connections\Provider($this->config);
  $this->provider->auth()->attempt($username, $password, $bind_as_user = true);
```

It works correctly but I'm not sure it's correct like that.

Thanks

**Comment by ciadch** [comment]
Another important point for me. I really need to set config as object because I need to set base_dn after authentication

**Comment by ciadch** [comment]
So, I continue, Is this config correct ? 
```php
	public function __construct() {
		
		// Construct new connexion
		$this->options		= Config::get('ldap_connexion_options');
		$this->connection	= parent::__construct(array('p1' => $this->options));
		$this->config 		= new Configuration\DomainConfiguration($this->options);
		$this->provider 	= new Connections\Provider($this->config, $this->connection);
		$this->setDefaultProvider('p1');
```

**Comment by stevebauman** [comment]
Hi @ciadch,

If you're wanting the user to run LDAP operations instead of a user configured in your configuration object, then this is definitely the option you'd like to use.

Passing in the third parameter performs a `ldap_bind()` to your LDAP server and **does not** perform a rebind to a user that you have configured inside the configuration object.

Using this method also validates that the username and password given are not empty strings or  `null` values by throwing exceptions:

https://github.com/Adldap2/Adldap2/blob/master/src/Auth/Guard.php#L41

Using the `bind()` method alone would achieve the same effect, but it **does not** validate their username and password:

https://github.com/Adldap2/Adldap2/blob/master/src/Auth/Guard.php#L73-L80

**Comment by ciadch** [comment]
Hi @stevebauman,

Thanks for your answer. I'll investigate what is the best for me.
