### ISSUE TITLE
findByDn() and option in()

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#513]
Hello,

It's seems there's a strange behaviour with in() and findByDn(). When I try that : 
```php
$adldap->provider->search()->in('OU=TEST,DC=test,DC=lab')->users()->findByDn('CN=test,OU=TEST2,DC=test,DC=lab'); 
```
The method returns the user whereas he is not in the same OU. It is a bug or a normal behaviour ? 

Thanks for your reply

**Comment by ciadch** [comment]
What I'm looking for in attribute which is unik (like GUID or SID) and the same for all objects. It's why I use DN. I use this attribute to find ldap account details

**Comment by stevebauman** [comment]
Hi @ciadch, this is because the `findByDn()` method overrides your base DN you've set with `in()`:

https://github.com/Adldap2/Adldap2/blob/master/src/Query/Builder.php#L538-L545

This is expected behavior, because to find a record in your directory by its distinguished name, an `ldap_read()` is performed, which accepts the distinguished name of the record you're looking for.

Distinguished names are unique per domain, so you don't need to specify an `in()` to scope it to an OU.

**Comment by stevebauman** [comment]
A distinguished name can be a good identifier, but if you want something globally unique, use their GUID:

```php
$user = $provider->search()->users()->whereCn('jdoe')->first();

// The string representation of the users GUID:
$guid = $user->getConvertedGuid();

// Finding a user by GUID:
$user = $provider->search()->findByGuid($guid);
```

**Comment by ciadch** [comment]
Hi @stevebauman,

Thanks for your return. I effectively user GUID now with in(). It works perfectly.
