### ISSUE TITLE
Avoid Illuminate\Support

### ISSUE THREAD

**Issue by christianmalek** [Adldap2/Adldap2#516]
Illuminate\Support comes with several helper functions which pollute the global namespace and causes several other conflicts. Matt Allan describes it wonderful in this blog post: http://mattallan.org/posts/dont-use-illuminate-support/

If I checked properly Adldap2 "only" needs this package for array and collection handling.
So maybe https://github.com/DusanKasan/Knapsack would be an alternative?

I just wanted to drop my two cents. This shouldn't harass you to change it. It's just that in several situations the usage of Illuminate\Support makes things pretty pesky.

**Comment by stevebauman** [comment]
Hi @christianmalek,

I've read this article, and I definitely agree that `illuminate/support` brings in way too much for other applications that don't use Laravel, but I haven't really found a good solution yet.

Due to the popularity of Laravel, I decided to use the support package to increase usability with developers so I could use its helper functions as well as the awesome collections it provides.

I may use [tightenco's collect package](https://github.com/tightenco/collect), but still undecided.

I'll leave this open for anyone's thoughts (as well as my own), as I agree something needs to be done to reduce the global namespace pollution for non-laravel projects.

**Comment by stuntguy3000** [comment]
I agree, this namespace pollution does actually cause issues and bulk. I would really appreciate changing this.

**Comment by stevebauman** [comment]
Will have a new release out today that removes the illuminate/support requirement and replaces it with tightenco/collect.

Thanks for your patience! :smile:
