### ISSUE TITLE
[Question] What sort of hashing is used when sending passwords? 

### ISSUE THREAD

**Issue by patrickcurl** [Adldap2/Adldap2#522]
- Adldap2 Version: 8.1
- LDAP Type: OpenLDAP
- PHP Version: 7.1.9

### Description:
I'm wondering what sort of hashing for passwords is used when sending the password via the user model. 

Thanks,

**Comment by stevebauman** [comment]
Hi @patrickcurl,

Passwords aren't hashed when being updated, they are encoded:

https://github.com/Adldap2/Adldap2/blob/master/src/Models/User.php#L1137-L1165

For example:
```php
$modifications[] = $this->newBatchModification(
    $attribute,
    LDAP_MODIFY_BATCH_REMOVE,
    [Utilities::encodePassword($oldPassword)]
);
```

https://github.com/Adldap2/Adldap2/blob/master/src/Utilities.php#L159-L169

Since changing passwords requires an SSL connection and LDAP variants don't allow sending hashed passwords (since they hash them themselves), this is a secure route for resetting and updating passwords.

If you need any further information just give me a shout, thanks!
