### ISSUE TITLE
Finding user by username returns wrong user

### ISSUE THREAD

**Issue by dico** [Adldap2/Adldap2#526]
- Adldap2 Version: v8.1.3
- LDAP Type: Active Directory
- PHP Version: 7.0.22-0ubuntu0.16.04.1

### Description:
What is the best way to query a user by username?

### Steps To Reproduce:
Using this:
`$record = $this->provider->search()->find('0101ab');`
returns user 0101ab**c**. Both users exists in AD, but it looks like there is a default wildcard search with this method?

**Comment by dico** [comment]
Using:
`$record = $this->provider->search()->findBy('samaccountname', $username);`
seem to do the trick, but I would appreciate any feedback if this is safe enough, to prevent any other mismatch in the future :-)

**Comment by stevebauman** [comment]
Hi @dico, this is intended.

The `find()` method uses ambiguous naming resolution (`anr`), so it's basically up to the server which record it finds most suitable to return.

https://github.com/Adldap2/Adldap2/blob/master/docs/query-builder.md#finding-a-specific-record

This is described in the above docs link, but I'll modify the note to be a little more explicit on this.

You're right to use the `findBy()` method, as you're looking for specific users by `samaccountname` since no two users in a single domain can have the same `samaccountname`.

I hope that answers your question! :smile:
