### ISSUE TITLE
Create Microsoft Exchange mailboxes

### ISSUE THREAD

**Issue by valentinstudent** [Adldap2/Adldap2#528]
- Adldap2 Version: 8.0
- LDAP Type: Active Directory
- PHP Version: 7.0.27

Hello :-) 

Is it possible to create Exchange mailboxes with this library ?

Thank you in advance

**Comment by valentinstudent** [comment]
@stevebauman  :)

**Comment by stevebauman** [comment]
Hi @valentinstudent, this is definitely possible, but it's not built into Adldap2.

You can create any LDAP record using this package even if there is no method defined for it, you'll just have to set the values yourself instead of Adldap2 filling them in for you.

I've never personally created one, so unfortunately I can't walk you through what attributes to set, so you'll have to look online for this.

Here's an example though making a blank LDAP record:

```php
$mailbox = $provider->make()->entry();

$mailbox->homeMdb = '';
// ...

$mailbox->save();
```
