### ISSUE TITLE
Call to undefined method Adldap\Laravel\Facades\Adldap::addProvider()

### ISSUE THREAD

**Issue by ivanseptian** [Adldap2/Adldap2#529]
- Adldap2 Version: 3.*
- LDAP Type: 
- PHP Version: 7.2

### Description:
I followed the instructions for Laravel 5.5 but im getting the following error:
Call to undefined method Adldap\Laravel\Facades\Adldap::addProvider()

**Comment by stevebauman** [comment]
Hi @ivanseptian,

Can you post your exact usage? It sounds like the package wasn't registered properly, since all a facade does is redirect your calls to the underlying object, which isn't happening here.

Also, this should be posted on the [Adldap2-Laravel](https://github.com/Adldap2/Adldap2-Laravel) repository, but since this is your first issue, it's okay.

**Comment by shafarizkyf** [comment]
have same issue, 
adldap 3.0
$ad = new Adldap();
$ad->addProvider($config) //ok
adldap 4.0 //didn't work

could you please tell me whats wrong here ?

**Comment by stevebauman** [comment]
Hi @shafarizkyf, are you importing Adldap?

```php
use Adldap\Adldap;

$ad = new Adldap();
$ad->addProvider($config);
```

Nothing has removed this method. Your application must be the cause.

If you still encounter issues please create one and I'll be happy to help :).

**Comment by shafarizkyf** [comment]
thank you @stevebauman 
i follow in the documentation
use Adldap\Laravel\Facades\Adldap;
but after u mention it
use Adldap\Adldap;
all works, thanks!
