### ISSUE TITLE
ldap_connect(): Could not create session handle fail in PHP 7.2

### ISSUE THREAD

**Issue by maxpower9000** [Adldap2/Adldap2#533]
- Adldap2 Version: 8.1.3
- LDAP Type: Active Directory
- PHP Version: 7.2 (WAMP)

### Description:

From PHP 7.2.0 throught 7.2.4 I get this PHP warning:

```php
ldap_connect(): Could not create session handle
```

No issues with PHP 7.1.15 or before.

php.net lists the following changes in their [ChangeLog](http://php.net/ChangeLog-7.php)

**LDAP:**
- Implemented FR #69445 (Support for LDAP EXOP operations)
- Fixed support for LDAP_OPT_SERVER_CONTROLS and LDAP_OPT_CLIENT_CONTROLS in ldap_get_option
- Fixed passing an empty array to ldap_set_option for client or server controls.

**Session:**
- Fixed bug #73461 (Prohibit session save handler recursion).
- PR #2233 Removed register_globals related code and "!" can be used as $_SESSION key name.
- Improved bug #73100 fix. 'user' save handler can only be set by session_set_save_handler()
- Fixed bug #74514 (5 session functions incorrectly warn when calling in read-only/getter mode).
- Fixed bug #74936 (session_cache_expire/cache_limiter/save_path() trigger a warning in read mode).
- Fixed bug #74941 (session fails to start after having headers sent).

### Steps To Reproduce:

Use PHP 7.2.0 throught 7.2.4

### Full setup

Win 7 Pro WAMP Server 3.1.3 32bit
Apache 2.4.33 PHP 7.2.0
nette Framework App

**Comment by stevebauman** [comment]
Hi @maxpower9000,

What are you providing as host names in your configuration?

These must be IP addresses or host names of your LDAP servers. No ports or prefixes should be applied here.

**Comment by stevebauman** [comment]
No problem @maxpower9000!

Strange! Are there any other details to the exception at all? Maybe in your PHP error log?

I'll try a blank setup with PHP 7.2.0 and see if I can reproduce.

**Comment by maxpower9000** [comment]
@stevebauman 

![callstack](https://user-images.githubusercontent.com/1230045/39508891-6630ffe8-4de4-11e8-9d6b-b9e21075aa83.PNG)

**Comment by prueckl** [comment]
I had an issue with the same error message.
The problem was that apache2 uses another version of `libsasl.dll` than php.

`ldap_int_sasl_init: SASL library version mismatch: expected 2.1.27, got 2.1.25`

After updating the lib in the apache2/bin directory the failure has gone away.

**Comment by maxpower9000** [comment]
@prueckl Thanks for your suggestion!

**apache and php using the same dll**

Inside `C:\wamp\bin\apache\apache2.4.33\bin` there is a symlink to the `libsasl.dll` located at `C:\wamp\bin\php\php7.2.6` ... therefore both *apache* as well as *php* should always be using the exact same dll, wouldn't you agree?

**libsasl version used**

It seems as though *php7.1* uses *libsasl* version `2.1.25`, whereas *php7.2* employs `2.1.27`.

**SOLVED (unknow reasons)**

It now runs as expected. No issue anymore. Neither when running *php* on `7.1.18` nor `7.2.6`. I don't really know why, but the *nette* framework vendor packages had a few upgrades as well, so imagine ... somewhere somehow things now are in agreement with each other.

**Comment by webpuppies** [comment]
Hi, I tried to duplicate the dll file to both folders (php and apache) but the same error still displays.

I'm using WAMPSERVER 3.1.3
Apache 2.4.33
PHP 7.2.4

**Comment by YetiCGN** [comment]
Thanks! That was very helpful for me and solved the problem on PHP 7.2 as well as 7.3, which still uses libsasl.dll version `2.1.27`.

**Comment by RepulsiveCoder** [comment]
### Thanks. That was very helpful for me.

**LDAP was running fine in php command line** but in website it was giving error (_No matter whether I run httpd.exe as service or from command line and changing versions of PHP and Apache up to several years older didn't help_)

_Apache Error Log: ldap_int_sasl_init: SASL library version mismatch: expected 2.1.27, got 2.1.25_

I am using all latest builds
PHP 8.1.9
httpd-2.4.54-win64-VS16.zip from Apache Lounge
MySQL Server 8.0.30
Windows 10 64 bit

Copying "libsasl.dll" to Apache24\bin Directory was a solution but that was not what I intend to do ...

As the libsasl.dll was not present in Apache bin directory; so the issue was in somewhere else.

The actual problem was found in **MySQL Server 8.0.30** and **Environment PATH Variable** order. MySQL was at upper order than PHP in PATH and there is a libsasl.dll in MySQL bin directory, so Apache was picking that up. _As I recently upgraded MYSQL from 8.0.29 to 8.0.30, previous version didn't have libsasl.dll in  bin directory so everything was running fine earlier._

**Solution: I just make sure PHP is on higher order than MySQL at PATH variable and the problem is solved for me**

_Apache is running as service so after editing the System Environment Variables I had to restart the machine._

Sorry for the long post, as it took me almost a day to figure this out, I shared my experience.
