### ISSUE TITLE
Adding groups while creating user

### ISSUE THREAD

**Issue by TipTopNick** [Adldap2/Adldap2#546]
- Adldap2 Version: 8.1.5
- LDAP Type: Active Directory
- PHP Version: 7.2

I have a admin form that our 'LDAP Admin' can fill out and it adds a new user to our Active Directory.  Everything seems to work great on it except for adding groups to the new user.  Upon trying to add (existing) groups to the user by using `$ldapUser->addGroup($ldapGroup);` we get a `ldap_modify_batch(): Batch Modify: No such object` error.

I believe this has something to do with the user not saved yet in Active Directory, `$ldapUser->save()` is not called until after trying to addGroup().

I also have an admin form for adding new groups and I CAN add users to the new group before saving by using the `$group->setMembers($members)` function :100:  which adds a members array to the group object so when it's created it adds any users to the group. 

I'm wondering if there is a way or something I'm missing to add groups to the user object (like a setGroups() function that works like setMembers() on the group object) so we can add groups that will be included after we save() the user.

**Comment by stevebauman** [comment]
Hi @TipTopNick,

You can't add not yet existing users to groups. You will need to save them prior to adding them.

When adding members to a group in LDAP, each member being added needs to exist because they need to have a distinguished name, which non-existing users do not have yet.

The reason this works when creating groups is because the users you're adding to it exist, and the group itself does not. 

The `addGroup()` method on user models actually calls upon the group itself, and then tries to add the users distinguished name *into* the group, which the user does not have:

https://github.com/Adldap2/Adldap2/blob/master/src/Models/Concerns/HasMemberOf.php#L28-L30

There is no way around this unfortunately. You will need to save the user first so it has a distinguished name, and then add them into groups they require.
