### ISSUE TITLE
List all groups defined within Active Directory

### ISSUE THREAD

**Issue by badgerfruit** [Adldap2/Adldap2#563]
adldap2/adldap2                       v8.1.5  A PHP LDAP Package for humans.
adldap2/adldap2-laravel               v4.0.7  LDAP Authentication & Management for Laravel.

Hello, using Laravel 5.6 (PHP 7) and the excellent ADLDAP, I wish to get a list of all Groups held within our Active Directory that are under the OU 'UserGroups'.

I've tried such fancy queries as

$groups = Adldap::search()->groups();

or

$groups = Adldap::search()->groups()->all();

or 

$groups = Adldap::search()->groups()->find('*');

But I either get errors or, in the case of the first query, a very unusual resultset (which does actually seem to contain the information, just in a very strange way (for example, if the user is a member of 10 groups, it gives me an 10 objects, each object having 10 sub-objects - these sub-objects are the groups that the user is a member of.  Likewise, if the user is a member of 20 groups, I get 20 objects each with 20 sub-objects!).

I've tried adding "first()", "get()" and all the other things I can think of onto the ends of the above queries to no avail.

Google doesn't seem to offer any help either so I'm sorry to create an issue here but I think it's my only option right now!

Thank you!

**Comment by stevebauman** [comment]
Hi @badgerfruit,

I believe your issue may be your configured `base_dn` judging by your second comment.

The `setDn()` method sets the base distinguished name for the search itself, so if your original queries in your first comment above return an inconsistent list, your base DN is set incorrectly.

Your `base_dn` should be `dc=network,dc=MyCompany,dc=com`, and not include any organizational units if you're looking to search the **entire** scope of your directory.

Otherwise, **if you do include organizational units** into your base DN, then your searches will only return objects that are located **inside** that organizational unit.

Hope this helps!
