### ISSUE TITLE
Roadmap & Depreciated functions

### ISSUE THREAD

**Issue by stevebauman** [Adldap2/Adldap2#6]
This is just an issue to track the roadmap and depreciated functions that are going to be removed in `5.1` when `5.0` is released. This will be consistently updated and then merged with the final documentation.

Depreciated functions so far:
- `$adldap->adldap_schema()`
- All `infoCollection()` functions
- `ldapSlashes()` on Utils class

Roadmap:

Above `5.1` (most likely in another major release), I'm most likely going to be looking at changing the class names and namespaces of the whole repository. Right now the names are an ugly mess of upper and lowercase, making it incompatible with PSR standards.

**Comment by stevebauman** [comment]
Actually, since class names and namespace are case insensitive, I should be able to make the package PSR compatible without breaking changes. Does anyone have any input on if this change would cause issue? Unfortunately I'm away from my computer so I'm unable to test, for example:

Changing `namespace adLDAP` to `namespace Adldap`

**Comment by samwilson** [comment]
Could it possibly be an issue for people not using the Composer autoloader? I'm not sure.

**Comment by stevebauman** [comment]
I think that's the only issue here, since the `require()` function is using the native file-system case sensitivity. Though support for requiring only one file has been dropped in 5.0, so if users are not using an auto-loader, they'll have to require the files manually anyway.

I'm going to experiment here and see if there are any issues with making namespaces and class names PSR compatible.

**Comment by stevebauman** [comment]
Ok, after lots of testing, we've reached PSR-4 compatibility, and it's good to go. I've only re-cased the namespaces and class names from `adLDAP` to `Adldap`. I've also renamed the organization and the package to follow the re-casing of the name to keep absolute consistency.

**Comment by strebl** [comment]
Great Job!

**Comment by samwilson** [comment]
Yes, this is terrific :)

**Comment by stevebauman** [comment]
Thanks! I'm almost finished with modifications to the package, once that's done, I'll be finishing up with testing, then comes documentation and release.

**Comment by ChadSikorra** [comment]
@stevebauman Namespaces and classnames may be case-insensitive as far as PHP is concerned, but it will also depend on your auto-loader and what OS you're running. Windows is case-insensitive by default, so it wouldn't matter there. But on Linux, changing the case would cause the auto-loader to fail to lookup the files correctly. Though it's probably a necessary evil in order to fix the mess.

**Comment by stevebauman** [comment]
Yea your right, unfortunately I only develop on Windows so I'm unable to test on linux (besides using Travis-CI of course).

And yea your right, Adldap v4 is literally a complete mess, there's no getting around it, and developers planning to move from v4 to v5 will <b>definitely</b> have to re-write some things, but the majority of the API will stay in-tact. Though we are doing a complete version jump here, so developers who are versed in semver will already know this version will have incompatibilities.

If anyone has any comments or feedback of API changes and additions, this is a great time to be vocal since once v5.0 is released, it's API will be in place for quite some time.

**Comment by stevebauman** [comment]
All `infoCollection()` functions on classes (as well as all Collection classes) are now depreciated (not removed). The majority of frameworks contain extendable `Collection` classes. Developers can wrap the returned arrays into their own object collections. I feel like this is the necessary way to go to keep framework agnosticism, however I'd definitely appreciate some feedback if anyone has any other suggestions, thanks! :)

**Comment by trinet-at** [comment]
I'm still struggling a bit with the consistency of the public API and general interfaces. For example:

We have `Users` and `User`.
When I do a `Users::find()` I would expect to get an array of `User` objects (aka. `User[]`). Instead I get one single `User` object. So, maybe we should introduce `findOne()`, `findMany()` or similar. `find()` shouldn't return a single object. Changing `find()` would break existing APIs, though.

Moreover, the `find()` method uses [ANR](http://social.technet.microsoft.com/wiki/contents/articles/22653.active-directory-ambiguous-name-resolution.aspx), which is good, but can deliver multiple results. `find()` just blindly returns the first result. If I search for 'thomas' and there are more person objects in the AD, I'll get just any one of them (perhaps alphabetically).
That's quite unpredictable. If I expect a single result and my search gets more than one, an Exception should be thrown.

Additionally, lots of the method's DocBlocks just hint `array` as return value, which sometimes is [just wrong](https://github.com/Adldap2/Adldap2/blob/master/src/Classes/Users.php#L50), and sometimes should be replaced with the name of the object with square brackets (`[]`) appended.

It's also unnecessary to return raw attribute values, when we have an appropriate object and could return that instead. for example: if I have a `User` object and want to get the groups the User is a member of, I would like to get an array of `Group` (`Group[]`) and not an array of raw DN strings (ugh).
That would mean we have to inject the current `Adldap` instance to perform (lazy) queries for the DNs of the groups. Some refactoring is required for that and it also changes the API: Instead of the `Connection`, the `Adldap` instance has to be passed to `Entry`.

Those are just suggestions and of course open for discussion. I'd be happy to do some of the refactoring, but first we should decide which way to go and if we want to change the public API again.

Those changes would lead to the direction that people using this library don't have to know too much about LDAP and it's structures. I think, that's the way this library should go.
I'll use this library for some projects and would have to write a wrapper for above issues to get a fluent coding experience, so why don't incorporate the changes directly to this library?

So, what to do? Just fix stuff that doesn't change the API, like DocBlocks, Exceptions, additional methos and postpone BCs to v6.0.0 or incorporate some of the changes right away?

Thanks!

**Comment by stevebauman** [comment]
Hi @trinet-at, I'll respond to each of your concerns.

##### `find()` returning one result instead of an array

I personally believe this is the right way to go. Calling a find method should *always* return one result. Developers are free to use `get()` when they need more than one. Though I understand filtering users by specific attributes isn't possible with the classes right now, but I'm working on it. Introducing a `findMany()` would cause confusion, as it would essentially be returning a `get()`.

##### `find()` uses ANR

I also believe this is the right way to go. Users can enter in any unique field that a user has (such as `sAMaccountname`). If developers are blindly asking for a user named thomas, then yes, they will receive the first result, but it's up to them to make sure they're querying a unique value. They're also free to use `$ad->search()->findByDn($dn)` which find a single record with the exact specified DN. But yes, this needs to be worked into the Users class as well.

##### Docblocks are wrong

Yes, sometimes they might be. You have to consider that I'm working on this single-handedly on my own free time and partly work time, not to mention it's still in beta. Notice an issue in a doc block? Send a PR.

##### Raw attribute values being returned

In your specific use case of group DN's being returned on a `User` object, performing a lazy load of groups could be very resource intensive. If an AD instance has a ton of nested groups, then we have to query recursive groups of groups, and instead of one query, we now have exponential depending on the number of groups a user is a member of. Not to mention, if a developer requests all users, do we request all groups on every single User instance? On a large enterprise, this could lead to hundreds of queries on one request.

I don't disagree that this should be done, but something needs to be in place to prevent mass queries taking place, maybe a `with('groups')` system like Laravel has to load relations.

##### Users not familiar with LDAP should use Adldap

I completely agree with this, and I'm really striving for a nice, easy to use API that anyone can start querying their server. I'm trying my best to make sure this is the case.

##### Break or not to break?

I think we still have a lot of room to make API changes, but definitely not large ones. Breaking changes should be done now in my opinion.

I appreciate you taking the time to write down your comments and concerns. I really enjoy working with a group of people to figure out which is the best way and to get something done. Any input anyone can provide is great.

If you have any PR's to send, definitely start firing them off!


- Steve

**Comment by trinet-at** [comment]
Hi!
Thanks for your comments!
First of all, I don't know if it came out wrong, but I really don't want to blame you for any flaws in the code. I know that you just adopted the library and really appreciate the work you put into it the last days. Lots of the code is "legacy" stuff and refactoring sometimes leads to wrong DocBlocks and as I said, I'm really happy to fix that things.

I just wanted to get a feeling of which way you want to go, so I won't submit a bunch of PRs which don't comply to your roadmap and would have to reject.

Regarding `find()`: You're totally right. `find()` should return one single result (Doctrine does that, too), and there are lots of options if one wants to search for multiple results (I'm still not that familiar with the code...)
Is it okay for you if, in such cases, I add a comment to the DocBlock of the method for clarification? I.e. add to the `find()` method, that it returns one single object, even if there's more than one result.

What do you think about convenience methods? For example in the `HasMemberOfTrait`:
```php
/**
 *  Returns an array of "pretty" group names, instead of DNs
 *
 * @return array
 */
function getGroupNames() {
    $memberOf = $this->getMemberOf();

    if (!$memberOf || empty($memberOf)) {
        return [];
    }

    unset ($memberOf['count']);
    $groupNames = [];

    foreach ($memberOf as $group) {
        $exploded = Utilities::explodeDn($group);
        $groupNames[] = Utilities::unescape($exploded[0]);
    }

    sort($groupNames, SORT_NATURAL);

    return $groupNames;
}
```

Thanks for your time!

**Comment by stevebauman** [comment]
@trinet-at That's no problem, I didn't take your comments as any offense at all!

I completely understand about submitting PR's, and I agree with your suggested `HasMemberOfTrait`, you can send a PR and I'll put it through. I'm all for convenience methods. Anything that helps the developer get the information they need is fine with me.
