### ISSUE TITLE
How to modify the name from OUs

### ISSUE THREAD

**Issue by kiqerdgz** [Adldap2/Adldap2#609]
Laravel Version: 5.2
PHP Version: 7.1
LDAP Type: Active Directory

### Description:
I need to modify the name from OUs but I can't find how to do this, can you help me?

### Steps To Reproduce:
1. Modify the name from OU

**Comment by stevebauman** [comment]
Hi @kiqerdgz,

You'll need to perform a `rename()` or `move()` on the Organizational Unit since your changing its name.

When you call the `move()` or `rename()` method, you need to provide it in a "relative distinguished name" format, which basically means "the part of the objects distinguished name that is its identifier":

```php
// For this example, the 'Accounting Users' OU's distinguished name
// is 'ou=Accounting Users,dc=acme,dc=org'
$ou = $provider->search()->ous()->find('Accounting Users');

// We want to rename it to: 'ou=All Users,dc=acme,dc=org'
$ou->rename('ou=All Users');
```

If you want to change the location **and** rename it, you need to provide the distinguished name of the container where the OU is going to be moved to and provide its new RDN:

```php
// For this example, the 'Accounting Users' OU's distinguished name
// is 'ou=Accounting Users,dc=acme,dc=org'
$ou = $provider->search()->ous()->find('Accounting Users');

// We want to move this OU into another OU named 'ou=Users,dc=acme,dc=org'.
// So the full DN should be 'ou=All Users,ou=Users,dc=acme,dc=org'
$ou->move('ou=All Users', 'ou=Users,dc=acme,dc=org');
```

Can you give that a shot and let me know if you run into issues? I will re-open if this is the case.

Thanks!

**Comment by kiqerdgz** [comment]
Hi Steve:

Thank you, I compiled this but in my case I hace two OU's with the same name in different locations and the code modify the name from the first OU that find, how can I do for find the correct OU and then modify it?
