### ISSUE TITLE
account_suffix on config username

### ISSUE THREAD

**Issue by eisbehr-** [Adldap2/Adldap2#610]
- Adldap2 Version: v9.1.3
- LDAP Type: Active Directory
- PHP Version: 7.1

### Description:
Config property `account_suffix` seems not to work on default credentials. But why not? On `attempt` there is no problem, but why not to support config user too?

### Steps To Reproduce:
```PHP
// didn't work
$adldap->addProvider([
    'username'       => 'test',
    'account_suffix' => '@mydomain.com',
]);

// works
$adldap->addProvider([
    'username'       => 'test@mydomain.com',
]);
```

**Comment by stevebauman** [comment]
Hi @eisbehr-,

This was intended on the release of `v9.0`: https://github.com/Adldap2/Adldap2/commit/28f7d85878e3bbbcbc2761a9d3a74df63b19a2c0

Developers using OpenLDAP or other LDAP distros sometimes have a different account suffix all together, as their configured admin account could be contained in an entirely different OU.

Take the following example:

```php
$adldap->addProvider([
    'username' => 'cn=admin,ou=administrators,dc=acme,dc=org',
    'password' => 'secret',

    'account_prefix' => 'cn=',
    'account_suffix' => ',ou=users,dc=acme,dc=org',
]);
```

In this scenario, we don't want the `account_suffix` or `account_prefix` applied to the configured username and password because it wouldn't be a valid DN.

There was previously the `admin_account_prefix` and `admin_account_suffix` options prior to `v9.0`, but this seemed pointless as it only affected the one account you were already configuring.

I didn't want to have a separate config option to disable this functionality either, I felt it was simpler to just have the configured username and password reside on their own, and have the `account_prefix` and `account_suffix` options only apply to `$provider->auth()->attempt()` methods.

**Comment by eisbehr-** [comment]
Thank you for you explanation @stevebauman !
Maybe add this little info to the docs on `account_suffix`? https://adldap2.github.io/Adldap2/#/setup?id=account-suffix
