### ISSUE TITLE
[Question] Why are almost all attributes returned as array?

### ISSUE THREAD

**Issue by HepplerDotNet** [Adldap2/Adldap2#624]
- Adldap2 Version: 9.1.4
- LDAP Type: Active Directory
- PHP Version: 7.2.11

I'm just wondering why almost all attributes are arrays? On attributes like SAMAccountName or givenname it doesn't make sense to return an array. Or is this behavior controlled by AD?

**Comment by stevebauman** [comment]
Hi @HepplerDotNet,

This is how all LDAP attributes are returned by PHP, as it doesn't know which attributes are multi-valued since it varies from each LDAP distribution.

Please see: http://php.net/manual/en/function.ldap-get-entries.php

You can use `$model->getFirstAtttribute('samaccountname')` to retrieve the first value of any model attribute.
