### ISSUE TITLE
BUG : BINDING AS ADMIN WITHOUT SUFFIX AND PREFIX

### ISSUE THREAD

**Issue by sharonco-matrix** [Adldap2/Adldap2#642]
- Adldap2 Version: 9.1.3
- LDAP Type: Active Directory 
- PHP Version: 7.2

### Description:
Missing add prefix and suffix for the bind as administrator and it throws an error and then we cannot connect
public function bindAsAdministrator()
    {

        $this->bind(
            **$this->applyPrefixAndSuffix(**$this->configuration->get('username')),
            $this->configuration->get('password')
        );
    }

### Steps To Reproduce:

If you have:
**login: sharon.cohen
password: pass
DisplayName: Sharon Cohen**
It returns authentication error

**login: sharon.cohen
password: pass
DisplayName: sharon.cohen**

It returns SUCCESS

Trying using $suffix with the @test.tester.com
first, it tries to bind as administrator without adding the prefix and the suffix and then it fails
Adding the $this->applyPrefixAndSuffix fixes the problem.
PLEASE ADVICE IF WE ARE DOING SOMETHING WRONG

**Comment by stevebauman** [comment]
Hi @sharonco-matrix,

This is intended. There was previously a configuration option for specifying the suffix and prefixes for your configured admin account used for binding to your LDAP server, however they were removed in the last major version (v9) due to the options being pointless as you can simply add the prefix or suffix onto the account name you configured.

The `account_suffix` and `account_prefix` options are **not** applied to the admin account username you configure as this caused issues with devs using alternate suffixes / prefixes for their admin account specifically.

It's described here in the documentation, admittedly not clear enough though:

https://adldap2.github.io/Adldap2/#/setup?id=account-prefix
https://adldap2.github.io/Adldap2/#/setup?id=account-suffix

To resolve your issue, simply add your prefix or suffix onto your configured admin account username. I will also update the documentation to reflect this more clearly.

Thanks!
