### ISSUE TITLE
Encrypt user and password

### ISSUE THREAD

**Issue by inncubusss** [Adldap2/Adldap2#652]
- Laravel Version: 5.8
- Adldap2 Version: 6.0.1
- LDAP Type: Active Directory
- PHP Version: 7.21

### Description:
Hi Steve, it is possible to save the encrypted LDAP_USERNAME and LDAP_PASSWORD in ldap.php?, then decrypt them when using the command:

Artisan::call("adldap:import", ['--no-interaction']);

I have a cron that must to run evey week and import the users from AD to my local DB, and this is the command I am using, but I have not found what changes exactly to do in this case for using user and password encrypted without crash the ADLDAP2 core.

Thnak you,

**Comment by stevebauman** [comment]
Hi @inncubusss,

Typically you would use environment variables (inside your `.env` file) to allow the command to run successfully with a scheduled job:

```
// .env

LDAP_HOSTS=192.168.1.1
LDAP_USERNAME=account@corp.acme.org
LDAP_PASSWORD=super-secret
LDAP_BASE_DN="dc=corp,dc=acme,dc=org"
```

This is secure because only you should have access to the `.env` file on the server (hence why your database username and password are also stored in this file).

However, if you want to encrypt the username and password, you will have to store the encrypted username and password somewhere, likely in your database or cache and then decrypt them at runtime.

Here's some pseudo script using a `settings` database table:

```php
Setting::create([
    'name' => 'ldap_username',
    'value' => encrypt('my-username')
]);

Setting::create([
    'name' => 'ldap_password',
    'value' => encrypt('super-secret')
]);
```

Then in your `App\Console\Kernel.php`, you will:

1. Retrieve the encrypted settings from your database
2. Decrypt them
3. Override username and password in your configuration at runtime

Upon calling the `adldap:import` command, the LDAP connection will use the overridden username and password.

```php
/**
 * Define the application's command schedule.
 *
 * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
 * @return void
 */
protected function schedule(Schedule $schedule)
{
    $username = Setting::whereName('ldap_username')->first();
    $password = Setting::whereName('ldap_password')->first();

    config()->set('ldap.connections.default.settings.username', decrypt($username->value));
    config()->set('ldap.connections.default.settings.password', decrypt($password->value));

    $schedule->command('adldap:import', ['--no-interaction'])
              ->hourly();
}
```

I can't help you write an implementation as that is beyond the scope of this issue and every application is different. I hope this helps! :smile:

**Comment by inncubusss** [comment]
Thank you for your quick response , I keep testing with your valuable recommendations
