### ISSUE TITLE
Scoped Queries from static method calls on models

### ISSUE THREAD

**Issue by jspringe** [Adldap2/Adldap2#675]
- Adldap2 Version: master
- LDAP Type: any
- PHP Version: 7.2.18

Possible feature request. I wanted to get your opinion on [this commit](https://github.com/jspringe/Adldap2/commit/34c5782cebd5b918c38b51c59eaf4b7815b8f517).

This is just a quick POC. Didn't want to go too far down the rabbit-hole before getting your feelings on it.

    new Adldap($config);
    User::query($provider_name = null)->where()...

Ideally I would move this down to the `Model` class and I was thinking of setting up all of the starting queries as statics that would do the same thing and return a scoped query based on some mapping from `get_called_class`. This way once you have initialized `Adldap` all you would have to do is call `Computer::where(...)` or whatever model you are interested in.

And actually.. I think Laravel proxies those static calls directly to the builder.. so I might not even need to add them onto the Model.

I would leave `query` so that if you needed to change from the default provider you could still do so using that method.

**Comment by jspringe** [comment]
I've actually updated it to [this commit](https://github.com/jspringe/Adldap2/commit/367a4e33c1eb7a2c9e670cc1c162af3ccfac4022).

This is using the `__callStatic` magic method to proxy the calls to the appropriate `Factory` scope then to the `Builder`.

Simpler change and same results.

**Comment by stevebauman** [comment]
Hey @jspringe, this is an awesome feature! Great work!

I was really wanting to add this type of functionality in to closely resemble Laravel's model structure and query building utilizing the model classes themselves - I just wasn't sure how I could implement it, but I think your solution is great.

This will give us the best of both worlds - creating queries through the provider itself, or through the models.

I'll merge this in and make some small formatting tweaks and some more tests.

Thanks!

**Comment by jspringe** [comment]
I am able to create a pull-request, but I realized that there is a potential issue here.

The problem is around the interface for Adldap. Is this necessary? I personally do not think so. It's the entry point for the library and unlike Laravel's application you don't need to worry about branching to either a CLI or HTTP version of it. I think you stay opinionated and say that if you use this library then Adldap is the entry point. It can be refactored later to be less so if a need arises. This means just deleting the interface.

I see that you use this to bind into Laravel's IOC container, but you could just as easily use Adldap::class.

If it stays then we need to create a container to implement this properly. This might be a little more complicated than a simple object, but I think I could implement it in a reasonable way. Similar to how Laravel lets you bind in your own concrete implementations at run-time.

If you have no issues with deleting the interface then I will create a PR in a few.

**Comment by stevebauman** [comment]
> The problem is around the interface for Adldap. Is this necessary?

Yes you're right, I was thinking it wouldn't be an issue to keep the interface. If someone created their own implementation they would then override the default models in their schema and then override the static `Model::query()` method which would return their own Adldap instance search factory - but this would be too much work for not much gain.

> If you have no issues with deleting the interface then I will create a PR in a few.

I don't have an issue with removing the interface - but doing so would mean we need to create a new major version of Adldap2 and Adldap2-Laravel to follow sem-ver.

I was hoping to migrate Adldap2 into its new name [LdapRecord](https://github.com/DirectoryTree) (unfinished) instead of releasing v11.0 so I could then have both repositories (LdapRecord & LdapRecord-Laravel) on the same version structure - i.e. when a new LdapRecord major version is released, a new LdapRecord-Laravel major version would also be released.

I'm in progress of completely re-working the documentation and have created its own docs site which is much cleaner (www.ldaprecord.com) and will have both packages documentation on the same site.

Maybe we could push this onto LdapRecord as a new feature - I think it would be perfect for it since it's being "marketed" as an ActiveRecord implementation.

What are your thoughts?

**Comment by jspringe** [comment]
[I had a slight change of heart about the approach.](https://github.com/jspringe/Adldap2/commit/e46fbe74262a2d554ed0120a8b183340092ff53f)

This keeps `Adldap` from behaving like a singleton and moves that responsibility to a `ProviderContainer`.

This doesn't change anything on public API and all tests pass as before.

I'm not going to remove the interface for now, because as you said if someone wants to go through the trouble of creating their own implementation there is a quite a bit of implied behavior that needs to be covered.

I feel like this _COULD_ be merged in place without breaking anything. Clean-up can happen on the new release under the new name.

I'll submit a PR.

**Comment by jspringe** [comment]
While this change _shouldn't­™_ be a breaking change and could be merged into 10.* - there is still a chance for odd behavior for those who instantiate `Adldap` more than once. I have some ideas on how to handle that, but they are all kinda grim. I'd rather just say "Don't instantiate more than one instance - just add more providers." but if someone has a good use case I could make it work.

Would you like me to re-implement this in that repository?
