### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by cschwehm** [Adldap2/Adldap2#688]
- Adldap2 Version: #.#  10.0.11
- LDAP Type:  Active Directory
- PHP Version: #.# 7.3.6

### Description:
Having issues getting installed.  Directions are not very clear.  I installed using composer as specified in root of web page where it is needed.  Is that correct place.  After doing this and trying to add to code have gotten variety of errors.  Latest is:

PHP Fatal error:  Trait 'Adldap\\Events\\DispatchesEvents' not found in /web-secure_a/sso/Adldap/Adldap.php on line 17

Did it install in wrong location or is there some type of path info I need to add some place?

**Comment by stevebauman** [comment]
Hi @cschwehm,

By the looks of your error, you haven't installed it properly using composer - otherwise the Adldap.php file would be located inside `/web-secure_a/vendor/adldap2/adldap2/src/Adldap.php`.

You can't download a ZIP of the Adldap2 files from GitHub and copy into your projects source. This is because Adldap2 has dependencies that composer downloads alongside it.

If you're not using a framework that utilizes composer, you must run `composer update` inside the root directory of your project that contains your `composer.json` file - this will download your projects dependencies.

Once done, you must require the composer autoloader in your `index.php` file - or whichever PHP file that is being loaded first from your web server via:

```php
require __DIR__ . '/vendor/autoload.php';

$ldap = new \Adldap\Adldap();

$ldap->addProvider(['...']);
```
