### ISSUE TITLE
How to get next page from pageinator?

### ISSUE THREAD

**Issue by Xento** [Adldap2/Adldap2#92]
As shown in your documentation I want to get all users from an ou and want to count howmany of them are in the same subou. Because it could be more than 10000 records I want to use pageination:

    $results = $ad->search()->select('dn')->where("sAMAccountType","=","805306368")->where('objectClass', '=', 'person')->where("userAccountControl:1.2.840.113556.1.4.803:", "!","2")->paginate(100, 0);

    $users = Array();
    foreach($results as $result)
    {
        $dn = explode(",", $result['attributes']['dn']);
        
        if(array_key_exists($dn[2], $users)){
            $users[$dn[2]]++;
        }
        else {
             $users[$dn[2]] = 1;
        }
    }

Whith this code I only get the first page.
I looked into the code and noticed, that you only return the first page when using this code.
There is an private function setCurrentPage(). 
When I change it to this:

    public function setCurrentPage($currentPage = 0)
    {
            $this->currentPage = (int) $currentPage;
            $this->setCurrentOffset(($this->getCurrentPage() * $this->getPerPage()));
     }

Then I can iterate over all apges using this code:

    $users = Array();
    for($page = 0; $results->getPages() > $page; $page++) {
        $results->setCurrentPage($page);
        
        foreach($results as $result)
        {
            $dn = explode(",", $result['attributes']['dn']);
            
            if(array_key_exists($dn[2], $users)){
                $users[$dn[2]]++;
            }
            else {
                 $users[$dn[2]] = 1;
            }
        }
    }

**Comment by stevebauman** [comment]
Hi @Xento, you're only seeing the first page of results because you're only asking for the first page in the `paginate()` method. The first argument is the amount of records you want per page, and the second is current page you're currently on. This is documented here:

https://github.com/Adldap2/Adldap2/blob/master/docs/SEARCH.md#paginate

However I'll show you an example:

```php
$perPage = 25;

$currentPage= $_GET['page'];

$users = Adldap::users()->search()->paginate($perPage, $currentPage);

// Iterate through the current page of users
foreach ($users as $user)
```

So if I hit my site with a page of zero (`http://localhost/users?page=0`), then I will see the first page of users. If I increment my page then I will see that page of users (`http://localhost/users?page=1`).

If you'd like to just display all pages on a single page, you'll have to get all the results by calling:

```php
$users = Adldap::users()->search()->paginate($perPage)->getResults();
```

**Comment by Xento** [comment]
Thank you. 
We need more documentation ;-)
Autocomplete did mit show this method.

**Comment by stevebauman** [comment]
There's always the API documention: http://adldap2.github.io/api/

You're also free to help document as well. Working on Adldap2 is not my full-time position so things may slip on an occasionally.
